### ISSUE TITLE
Allow paths to be named

### ISSUE THREAD

**Issue by VMRuiz** [BurnzZ/scrapy-loader-upkeep#1]
When having several amounts of xpaths for each field, is really difficult to determine which one was added firsts, specially when there are different workflows on the code.

To make easier the task to identify the paths on the stats, it would be great if we could name them. For example:

```python
loader.add_css('NAME', 'h1::text', name='Name from h1')
loader.add_css('NAME', 'meta[value="title"]::attr(content)', name="Name from meta tag")
```

**Comment by andrewbaxter** [comment]
What about putting the selector text in the stat path (maybe mangled)?  As a setting?

**Comment by BurnzZ** [comment]
Solid suggestion @VMRuiz!

At the moment, this is the current format of the stats:
`parser/{item_loader_class_name}/{field_name}/{css_or_xpath}/{parser_position}/{missing}`

which translates into the stats output:
```
{ ...
  'parser/QuotesItemLoader/author/css/1': 10,
  'parser/QuotesItemLoader/quote/css/1/missing': 10,
  'parser/QuotesItemLoader/quote/css/2': 10,
  ...
}
```

Adding in the **name** would be something like below in order to supplement the **parser_position**:
`parser/{item_loader_class_name}/{field_name}/{css_or_xpath}/{parser_position}/{name}/{missing}`

which should be along the lines of:
```
{ ...
  'parser/QuotesItemLoader/author/css/1/inside the div of the article': 10,
  'parser/QuotesItemLoader/quote/css/1/missing/main text located inside the text box': 10,
  'parser/QuotesItemLoader/quote/css/2/hidden div probably for SEO': 10,
  ...
}
```

Long **names** might cause the stats output to be a bit messy, but that's okay since there's now user identifiable context of the parser. Without the optional **name** param, we're limited to only **positional context** of when the `add_css()` or `add_xpath()` was called.

-----

@andrewbaxter, I like the idea of declaring the parser format as a setting, so users could easily override it to however they see fit.

We could declare the current format above as the default that is overridable by users in the settings, like:
`SCRAPY_LOADER_UPKEEP_STAT_FORMAT = 'my_own_stat_format/{missing}/{css_or_xpath}/{item_loader_class_name}/{field_name}/{parser_position}/{name}'`

Might not be the best API at the moment but the thought of having users customize their stats would really be great.

I'll draft up a PR for this feature. Cheers!

**Comment by BurnzZ** [comment]
Hey everyone!

I've started up a draft PR for this new feature.

------

When using this new **name** feature, users should be cognizant on how it should describe the parser, since we effectively have two ways of writing fallback parsers:

```
loader.add_css('NAME', 'h1::text', name='Name from h1')
loader.add_css('NAME', 'meta[value="title"]::attr(content)', name="Name from meta tag")
```

which would be something like:

```
{ ...
  'parser/QuotesItemLoader/NAME/css/1/Name from h1': 8,
  'parser/QuotesItemLoader/NAME/css/1/Name from h1/missing': 2,
  'parser/QuotesItemLoader/NAME/css/2/Name from meta tag': 7,
  'parser/QuotesItemLoader/NAME/css/2/Name from meta tag/missing': 3,
  ...
}
```

The other type of fallback parser which is grouped, such as:

```
loader.add_css(
    'NAME', 
    [
        'h1::text',
        'meta[value="title"]::attr(content)',
    ],
    name='NAMEs at the main content')

loader.add_css(
    'NAME',
    [
        'footer .name::text',
        'div.page-end span.name::text',
    ],
    name='NAMEs at the bottom of the page')
```

which translates into something like:

```
{ ...
  'parser/QuotesItemLoader/NAME/css/1/NAMEs at the main content': 8,
  'parser/QuotesItemLoader/NAME/css/1/NAMEs at the main content/missing': 2,
  'parser/QuotesItemLoader/NAME/css/2/NAMEs at the main content': 7,
  'parser/QuotesItemLoader/NAME/css/2/NAMEs at the main content/missing': 3,
  'parser/QuotesItemLoader/NAME/css/3/NAMEs at the bottom of the page': 8,
  'parser/QuotesItemLoader/NAME/css/3/NAMEs at the bottom of the page/missing': 2,
  'parser/QuotesItemLoader/NAME/css/4/NAMEs at the bottom of the page': 7,
  'parser/QuotesItemLoader/NAME/css/4/NAMEs at the bottom of the page/missing': 3,
  ...
}
```

**Comment by BurnzZ** [comment]
@VMRuiz , thanks again for the suggestion! Implementation has been released and the `README` file has been updated for this sweet new feature!

@andrewbaxter , the customizable format hasn't been included in the update, let's explore that instead in #4 :)
